### ISSUE TITLE
Improve the "Drupal Switzerland" title on the front page

### ISSUE THREAD

**Issue by dpacassi** [drupal-switzerland/drupal-ch#31]
- The font size should be decreased on mobile devices so that "Switzerland" doesn't break
- Increase text-shadow or add a transparent black background so that the contrast between the text and the background is increased (accessibility)

**Comment by VD39** [comment]
@dpacassi this has been done. Let me know if you think the background overlay should be darker.

**Comment by dpacassi** [comment]
I think we can easily go for `0 4px 20px rgba(0,0,0,0.95)`.
At the moment some contrast is in at a 6:1 ratio while WCAG level AAA requires a ratio of at least 7:1.

**Comment by VD39** [comment]
Font shadow is updated to use the suggested one above.

**Comment by VD39** [comment]
Closing this as the above has been done.
