### ISSUE TITLE
Mobile menu does not close for inpage navigation links

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-switzerland/drupal-ch#34]
On mobile, the menu overlay does not close if a menu item link uses in-page navigation such as: `<a href="#in-page-selector>Example</a>`

**Comment by VD39** [comment]
@dan2k3k4 The above has been done.

**Comment by dan2k3k4** [comment]
Tested but it still doesn't work

**Comment by VD39** [comment]
I noticed yesterday and I am trying to figure out why it works here: https://nginx-drupal-ch-master.ch.amazee.io/ but not on the live site. 🤔 It works locally too.

**Comment by dan2k3k4** [comment]
Hmm must be something with the cache setup

**Comment by dan2k3k4** [comment]
Seems OK now, thanks @VD39
