### ISSUE TITLE
links in nav don't work when on impressum/coc

### ISSUE THREAD

**Issue by felixhaeberle** [drupal-switzerland/drupal-ch#38]
links in nav don't work when on impressum/coc page because anchor links are used in the main nav and they don't work when not on the start page

**Comment by dan2k3k4** [comment]
Thanks @felixhaeberle, updated to `/#about-us` instead of `#about-us`

**Comment by felixhaeberle** [comment]
Great! Thank you! Great work on the site, looks really good 👏

**Comment by felixhaeberle** [comment]
uh, now the nav isn't closing on mobile 🙉

**Comment by VD39** [comment]
@felixhaeberle I noticed that, but you beat me to it. I will fix today.

**Comment by VD39** [comment]
@dan2k3k4 fixed it. Thanks.

**Comment by dan2k3k4** [comment]
Well, I only pushed a quick fix 😄 so matches on:
`/#about-us`
and
`#about-us`
but not:
`/page/test#about-us`

**Comment by VD39** [comment]
@dan2k3k4 I will push a fix for that later today.

**Comment by VD39** [comment]
Closing this as it has been fixed. URL is updated in the Twig template.
